# Generated by Django 4.0 on 2021-12-22 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productmodel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=400)),
                ('price', models.FloatField()),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
